### ISSUE TITLE
how does the sourceing work

### ISSUE THREAD

**Issue by FinnFrotscher** [Parth/dotfiles#37]
hi,
i tried to recreate you `~/dotfiles` folder layout. 
i cant get to rc files at `~` to work. 
they are `.chunkwmrc` and `.skhd` files.
is there a special language to know about? i just put `source /Users/Finn/dotfiles/chunkwmrc`, but it does not work.

**Comment by Parth** [comment]
Hi,
see [this](https://superuser.com/questions/46139/what-does-source-do) explanation of source.

But basically, the idea of source is to execute a given file *in the current context*. So for example if you were to have a script that defines a bunch of constants, and you execute that script normally, you'd expect those constants to not be available to the parent script. 

But if you source the script, those variables get added to the current context. 

 Depending on what program or process is consuming your run commands, the details of sourcing a file will be different (syntax as well as behavior). For example:

This is how I source a zsh file:
```
source '$HOME/dotfiles/zsh/zshrc_manager.sh'
```

And this is how I would source a vim file:
```
so $HOME/dotfiles/vim/vimrc.vim"
```

Feel free to re-open this and ask more questions if you're still confused.
