### ISSUE TITLE
tmux warnings

### ISSUE THREAD

**Issue by Parth** [Parth/dotfiles#38]
![image](https://user-images.githubusercontent.com/821972/38592406-d789d444-3d09-11e8-8457-51fd35587c19.png)

**Comment by mkucijan** [comment]
[](https://github.com/tmux/tmux/issues/754)

**Comment by Parth** [comment]
https://github.com/tmux/tmux/issues/754#issuecomment-297452143

**Comment by Parth** [comment]
This should be resolved now
