### ISSUE TITLE
Zsh Plugins not downloaded

### ISSUE THREAD

**Issue by ksemba** [Parth/dotfiles#52]
Hi folks,

I cloned the repo, ran the deploy script, logged out and in again. But I see errors that the zsh plugins cannot be sources since those files / folders don't exist locally. In particular, these folders don't have any content:
~/dotfiles/zsh/plugins/oh-my-zsh/
~/dotfiles/zsh/plugins/zsh-autosuggestions/      
~/dotfiles/zsh/plugins/zsh-syntax-highlighting

I manaed to manually clone those three repos and get everything working but I wanted to know what I was doing wrong?

**Comment by Parth** [comment]
Hey, can you tell me a bit about the system you did this on? I'll try to reproduce accordingly, and then see what's up.

**Comment by ksemba** [comment]
Sure. I'll start with the basics:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

This is not an out-of-the-box Ubuntu though. It is highly customized and that could be the reason that this doesn't work right away. I don't want you to bother with my custom setup but maybe if I better understand how the git clone would automatically pull in those dependent git projects I could look at why this might fail on my system. I saw that those git modules are also not included if you download the repo as zip file.

**Comment by Parth** [comment]
let me just grab a ubuntu vps from digital ocean and see what's up after work today

**Comment by leontedev** [comment]
I had the same issue on Mac - the zsh/plugins/oh-my-zsh is empty

**Comment by Oloyko** [comment]
Hi, I've had the same problem on my Ubuntu 19.04. But I remember that this
wasn't always the case, it worked a year ago or so.

Dne st 31. 7. 2019 9:22 uživatel Mihai Leonte <notifications@github.com>
napsal:

**Comment by Parth** [comment]
I found the issue, I changed the auto-updater to tell you what all changed, this broke the submodule pull. I'll push a fix soon.

**Comment by Parth** [comment]
Hey guys, this should be fixed now, can you please try again?
