### ISSUE TITLE
After running ./deploy on Mac and logging out and back in,  nothing is working. 

### ISSUE THREAD

**Issue by sleemCode** [Parth/dotfiles#57]
macOS Catalina Version 10.15
Cloned repo to my ~ directory. Running ./deploy seems all is working as expected as far the shell script. Closed/Opened a new terminal and nothing is working. Isn't this os independent? 

```
We're going to do the following:
1. Grab dependencies
2. Check to make sure you have zsh, vim, and tmux installed
3. We'll help you install them if you don't
4. We're going to check to see if your default shell is zsh
5. We'll try to change it if it's not
Let's get started? (y/n)

Checking to see if zsh is installed
zsh is installed.

Checking to see if vim is installed
vim is installed.

Checking to see if tmux is installed
tmux is installed.

Default shell is not zsh. Do you want to chsh -s $(which zsh)? (y/n)
Changing shell for rajasleem.
Password for ...: 
chsh: /usr/local/bin/zsh: non-standard shell

Would you like to backup your current dotfiles? (y/n) 
Not backing up old dotfiles.

Please log out and log back in for default shell to be initialized.
```

**Comment by Parth** [comment]
Yep, should be plug and play. Can you expand on "Nothing is working"? Do you get to zsh? Or are you still in bash? Does it say `Process Completed` or something like that?

**Comment by sleemCode** [comment]
I should have elaborated on "nothing is working" :-) 
After opening a new terminal, I am still on bash. 
on ~: 
vim .vimrc `so /Users/<username>/dotfiles/vim/vimrc.vim`
vim .zshrc `source /Users/<username>/dotfiles/zsh/zshrc.zshrc_manager.sh`
vim .tmux.conf `source-file /Users/<username>/dotfiles/tmux/tmux.conf`

if you need more information, please let me know. 

after done with running ./deploy, I did not see anything that says ```Process Completed```
```Please log out and log back in for default shell to be initialized.``` is the last prompt.

**Comment by Parth** [comment]
Hmm, seems like something went wrong during `chsh`. Could you manually try to:

```
chsh -s $(which zsh)
```

**Comment by Parth** [comment]
`chsh: /usr/local/bin/zsh: non-standard shell`

this is what went wrong. I should have seen this. Perhaps `deploy` should not imply that the operation was successful when this happens.

Okay so a few things that confuse me about your situation:

1. On macOS Catalina isn't the default shell already the default shell?
2. Why is your `zsh` there? 

So you could do: `echo $0` to figure out what your current shell is. Confirm that this is not `zsh`.

But to actually solve this problem:
1. Add  the output of `which zsh` (should evaluate to: `/usr/local/bin/zsh`) to `/etc/shells`
2. Either run `./deploy` again or `chsh -s $(which zsh)`

**Comment by Parth** [comment]
More context for further reading:

- https://github.com/thoughtbot/laptop/issues/447
- https://github.com/fish-shell/fish-shell/issues/989

**Comment by sleemCode** [comment]
tried changing login shell in Users & Group / Advanced Option to /usr/local/bin/zsh
when I open a new terminal:
```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
```

when I run `echo $0` => `-bash`
when I run `which zsh` => `/usr/local/bin/zsh`
when I run 'sudo cat /etc/shells':
```
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/usr/local/bin/zsh
/usr/local/bin/bash
``` 
when I run `chsh -s $(which zsh)` =still getting `chsh: /usr/local/bin/zsh: non-standard shell`

I read the links you provided, my take away is to append `/usr/local/bin/zsh` to `/etc/shells`, which it has been done already. What I am missing? Also, I do appreciate you trying to help me out. 👍

**Comment by Parth** [comment]
Yep, after appending that re-run `./deploy` and you should be good!

**Comment by Parth** [comment]
Maybe you need to logout/log back in?

**Comment by Parth** [comment]
if none of that works try `chsh -s /bin/zsh` <- this is what the original zsh not the one installed by brew

**Comment by Parth** [comment]
Any luck @sleemCode ?

**Comment by sleemCode** [comment]
I end up restarting my Mac and all started working. Sorry for my late reply and thank you for the awesome dotfiles.
