### ISSUE TITLE
Key binding for cd

### ISSUE THREAD

**Issue by dylanirlbeck** [Parth/dotfiles#58]
Hi. I really like your idea for remapping `cd` to `cd` and then `ls`, but I'm curious how I can add this functionality directly to my `.zshrc`. I see in your `zshrc.sh` script you do 

```shell
# Custom cd
chpwd() ls
```

but I'm not sure how to just put the remapped `cd` into my `.zshrc` like `alias -g cd="<STUFF>"`. 

Could anyone help me figure this out? Thanks in advance!

**Comment by Parth** [comment]
I believe that is all you need to do, is that not working for you?

https://github.com/Parth/dotfiles/commit/ab1e2b12103745465853c769e7ca45dde33285d5

This is how I used to do it and it caused some weird side effects.

**Comment by dylanirlbeck** [comment]
That was it, sorry for the confusion. I must have had another error in my `.zshrc` at the time that wasn't letting the file work. Thanks @Parth!
